### ISSUE TITLE
Create another channel

### ISSUE THREAD

**Issue by schotje0013** [DiscordSRV/Staff-Chat#14]
Hey,

I have used your staff chat and made it an admin chat.
I also would like a helpers chat, and i wonderd if there maybe was something possible with this?
To change some settings to have two of the same plugin running, (but one for helpers)

**Comment by RezzedUp** [comment]
There is currently no support for multiple channels, and there probably won't be. I'm personally not a fan of staff role-specific channels because it seems counter-productive to communication.

There's also no way to run two separate instances of this plugin (that is generally not supported by any plugin).
