### ISSUE TITLE
Separate staffchat.access into two permissions: staffchat.view & staffchat.chat

### ISSUE THREAD

**Issue by pkrok01** [DiscordSRV/Staff-Chat#7]
An example would be for members to be able to send in messages to staffchat to report any issues, while not being able to view staffchat. Might have other use cases.

**Comment by RezzedUp** [comment]
Interesting idea. However, this seems slightly outside the scope of this plugin's goal: facilitating chat between staff in-game and on discord. I can still be convinced otherwise, but right now I'm leaning toward not including it in DiscordSRV-Staff-Chat. This might be fit for a new plugin entirely, since this is one-way communication (players notifying staff).
